import { env } from "cloudflare:workers";
async function init(){const d=env.DB;await d.batch([d.prepare(`CREATE TABLE IF NOT EXISTS picks (id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,final_spain INTEGER NOT NULL,final_argentina INTEGER NOT NULL,bronze_france INTEGER NOT NULL,bronze_england INTEGER NOT NULL,champion TEXT NOT NULL,bonus TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL)`),d.prepare(`CREATE TABLE IF NOT EXISTS game_results (id INTEGER PRIMARY KEY,final_spain INTEGER,final_argentina INTEGER,bronze_france INTEGER,bronze_england INTEGER,champion TEXT NOT NULL DEFAULT '',bonus TEXT NOT NULL DEFAULT '')`)]);}

type EspnEvent={id:string;competitions:Array<{status:{type:{completed:boolean;description:string}};competitors:Array<{score:string;winner:boolean;team:{abbreviation:string;displayName:string}}>}>};
async function fetchEvent(date:string,eventId:string){const res=await fetch(`https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard?dates=${date}`,{cf:{cacheTtl:30,cacheEverything:true}});if(!res.ok)return null;const json=await res.json() as {events:EspnEvent[]};return json.events.find(e=>e.id===eventId)??null;}
async function firstScorer(eventId:string){const res=await fetch(`https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/summary?event=${eventId}`,{cf:{cacheTtl:300,cacheEverything:true}});if(!res.ok)return "";const json=await res.json() as {keyEvents?:Array<{scoringPlay?:boolean;shootout?:boolean;clock?:{value?:number};participants?:Array<{athlete?:{displayName?:string}}>}>};const goal=(json.keyEvents??[]).filter(e=>e.scoringPlay&&!e.shootout).sort((a,b)=>(a.clock?.value??0)-(b.clock?.value??0))[0];return goal?.participants?.[0]?.athlete?.displayName??"";}
function statusJa(value:string|undefined){if(!value)return "取得待ち";if(value==="Scheduled")return "試合前";if(value==="Full Time")return "終了・採点済み";if(value==="In Progress"||value==="Halftime")return "試合中";return value;}
async function syncOfficialResults(){try{const [bronze,final]=await Promise.all([fetchEvent("20260718","760516"),fetchEvent("20260719","760517")]);const current=await env.DB.prepare("SELECT final_spain AS finalSpain,final_argentina AS finalArgentina,bronze_france AS bronzeFrance,bronze_england AS bronzeEngland,champion,bonus FROM game_results WHERE id=1").first<Record<string,unknown>>()??{finalSpain:null,finalArgentina:null,bronzeFrance:null,bronzeEngland:null,champion:"",bonus:""};
  if(bronze?.competitions[0]?.status.type.completed){for(const c of bronze.competitions[0].competitors){if(c.team.abbreviation==="FRA")current.bronzeFrance=Number(c.score);if(c.team.abbreviation==="ENG")current.bronzeEngland=Number(c.score);}}
  if(final?.competitions[0]?.status.type.completed){for(const c of final.competitions[0].competitors){if(c.team.abbreviation==="ESP")current.finalSpain=Number(c.score);if(c.team.abbreviation==="ARG")current.finalArgentina=Number(c.score);if(c.winner)current.champion=c.team.abbreviation==="ESP"?"スペイン":"アルゼンチン";}current.bonus=await firstScorer("760517");}
  await env.DB.prepare(`INSERT INTO game_results (id,final_spain,final_argentina,bronze_france,bronze_england,champion,bonus) VALUES (1,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET final_spain=excluded.final_spain,final_argentina=excluded.final_argentina,bronze_france=excluded.bronze_france,bronze_england=excluded.bronze_england,champion=excluded.champion,bonus=excluded.bonus`).bind(current.finalSpain,current.finalArgentina,current.bronzeFrance,current.bronzeEngland,current.champion,current.bonus).run();return {bronze:statusJa(bronze?.competitions[0]?.status.type.description),final:statusJa(final?.competitions[0]?.status.type.description)};}catch{return {bronze:"取得待ち",final:"取得待ち"};}}
export async function GET(){await init();const official=await syncOfficialResults();const [p,r]=await Promise.all([env.DB.prepare("SELECT id,name,final_spain AS finalSpain,final_argentina AS finalArgentina,bronze_france AS bronzeFrance,bronze_england AS bronzeEngland,champion,bonus,created_at AS createdAt FROM picks ORDER BY created_at").all(),env.DB.prepare("SELECT final_spain AS finalSpain,final_argentina AS finalArgentina,bronze_france AS bronzeFrance,bronze_england AS bronzeEngland,champion,bonus FROM game_results WHERE id=1").first()]);return Response.json({picks:p.results,results:r??{finalSpain:null,finalArgentina:null,bronzeFrance:null,bronzeEngland:null,champion:"",bonus:""},official})}
export async function POST(req:Request){await init();const b=await req.json() as Record<string,unknown>;if(b.type!=="pick")return Response.json({error:"official results are automatic"},{status:403});const name=String(b.name??"").trim().slice(0,30);if(!name)return Response.json({error:"name required"},{status:400});const nums=[b.finalSpain,b.finalArgentina,b.bronzeFrance,b.bronzeEngland].map(Number);if(nums.some(n=>!Number.isInteger(n)||n<0||n>20))return Response.json({error:"invalid score"},{status:400});await env.DB.prepare("INSERT INTO picks (name,final_spain,final_argentina,bronze_france,bronze_england,champion,bonus,created_at) VALUES (?,?,?,?,?,?,?,?)").bind(name,...nums,String(b.champion??""),String(b.bonus??"").slice(0,60),new Date().toISOString()).run();return Response.json({ok:true})}
